resources:
- ../base
- postgres.yaml
- volumes.yaml

images:
- name: apache/airflow
  newTag: master-python3.7-ci-slim

configMapGenerator:
- name: airflow-configmap
  files:
  - airflow.cfg

secretGenerator:
- name: airflow-secrets
  envs:
  - dev.env
  type: Opaque

patchesStrategicMerge:
- patch.yaml

namePrefix: dev-