resources:
- ../base
- postgres.yaml
- volumes.yaml
- configmap.yaml

images:
- name: apache/airflow
  newTag: master-python3.7-ci-slim

secretGenerator:
- name: airflow-secrets
  envs:
  - dev.env
  type: Opaque

patchesStrategicMerge:
- patch.yaml

namePrefix: dev-